### ISSUE TITLE
(loophole-mode) is not useful.

### ISSUE THREAD

**Issue by bommbo** [0x60df/loophole#1]
I must disable loophole-mode and next enable loophole-mode.
example:
```
(use-package loophole
  :config
  (loophole-mode)
  (defvar loophole-comment-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "z") #'meow-comment)
    map)
  "Keymap for example.")

(defvar loophole-comment-map-state nil "State of `loophole-comment-map'")
(make-variable-buffer-local 'loophole-comment-map-state)

(loophole-register 'loophole-comment-map 'loophole-comment-map-state "n")
  )
```

**Comment by 0x60df** [comment]
I hope loophole-mode works well for you as you completed the issue.

As a supplementary information, `loophole-register` works no matter whether `loophole-mode` is enabled.
Actually, most Loophole facilities works independently of `loophole-mode`. What `loohpole-mode` does are `loophole-resume`, set up some key bindings, mode-line lighter, and variable-watcher which works only for speeding up internal process. You can use Loophole even without `loophole-mode` by calling `loophole-resume` if you don't need the bindings and mode-line lighter that `loohpole-mode` offers.

If you still have any problem, feel free to reopen the issue.
